In [1]:
import pandas as pd
import numpy as np

## Gaze Direction
data2load = pd.read_csv('/Users/dhewitt/Data/pps/Exports/ERD/PPSERDDataLong_180324.csv')

df = pd.DataFrame(data2load)

df

       SubjectID  ElectrodeID  Timebin  FreqBand  EEGPowerChange Block   Cue
0              2            1        1         4       17.475571  Cond  Pain
1              2            1        1         4       12.526318  Cond  Neut
2              2            1        1         4       13.066841  Extn  Pain
3              2            1        1         4       31.173826  Extn  Neut
4              3            1        1         4       14.132080  Cond  Pain
...          ...          ...      ...       ...             ...   ...   ...
39931         29           32        3        24       -4.466046  Extn  Neut
39932         30           32        3        24      -14.211909  Cond  Pain
39933         30           32        3        24      -24.697016  Cond  Neut
39934         30           32        3        24      -16.395248  Extn  Pain
39935         30           32        3        24      -10.259397  Extn  Neut

[39936 rows x 7 columns]

In [2]:
df=df.replace({'Cond':'1','Extn':'2','Pain':'1','Neut':'0'})

In [3]:
data2load = pd.read_csv('/Users/dhewitt/Data/pps/electrodeGroupings.csv')
sidesdf = pd.DataFrame(data2load)
sidesdf

    ElectrodeID  Grouping1  Grouping2  Grouping3  ElSide
0             1          1          1          1      -1
1             2          1          1        100      -1
2             3          1         10          1      -1
3             4          1         10          1       0
4             5          2          2          2      -1
5             6          3          3          3      -1
6             7          3          3          3       1
7             8          3          3          3       1
8             9          2          2          2       0
9            10          2          2          2      -1
10           11          4          4          4      -1
11           12          4          4          4       0
12           13          4          4        400       1
13           14          4          4          4      -1
14           15          4          4          4      -1
15           16          5          5          5       1
16           17          5          5          5       1
17           18          5          5          5       1
18           19          4          4         40       0
19           20          4          4         40      -1
20           21          6          6          6       1
21           22          4          4         40      -1
22           23          4          4         40       1
23           24          3          3        300       1
24           25          3          3         30      -1
25           26          6          6          6       1
26           27          6          6          6       1
27           28          3          3         30      -1
28           29          3          3         30      -1
29           30          1         10         10       1
30           31          1         10         10       1
31           32          1          1         10       1

In [4]:
df=df.join(sidesdf.set_index('ElectrodeID'), on='ElectrodeID')
df

,SubjectID,ElectrodeID,Timebin,FreqBand,EEGPowerChange,Block,Cue,Grouping1,Grouping2,Grouping3,ElSide
0,2,1,1,4,17.475571,1,1,1,1,1,-1
1,2,1,1,4,12.526318,1,0,1,1,1,-1
2,2,1,1,4,13.066841,2,1,1,1,1,-1
3,2,1,1,4,31.173826,2,0,1,1,1,-1
4,3,1,1,4,14.132080,1,1,1,1,1,-1
...,...,...,...,...,...,...,...,...,...,...,...
39931,29,32,3,24,-4.466046,2,0,1,1,10,1
39932,30,32,3,24,-14.211909,1,1,1,1,10,1
39933,30,32,3,24,-24.697016,1,0,1,1,10,1
39934,30,32,3,24,-16.395248,2,1,1,1,10,1
39935,30,32,3,24,-10.259397,2,0,1,1,10,1

In [5]:
df.to_csv('/Users/dhewitt/Data/pps/Exports/ERD/PPSERDDataLong_Grouped_180324.csv')

## Extinction sides data

In [34]:
data2load = pd.read_csv('/Users/dhewitt/Data/pps/Exports/ERD/PPSERDDataLong_noav_180324.csv') 
##this one has both left and right pain sides, and both repetitions, compared to data above

df = pd.DataFrame(data2load)
df.loc[df['EEGPowerChange']>=500]

,ID,ElectrodeID,Timebin,FreqBand,EEGPowerChange,Block,Cue,Rep,Side
5928,2,20,1,4,575.587594,Cond,Pain,1,L
19060,4,30,2,4,605.061530,Extn,Pain,1,R
54732,14,16,3,8,618.093032,Cond,Pain,1,L
55356,14,18,3,8,521.240289,Cond,Pain,1,L

In [35]:
df=df.replace({'Cond':'1','Extn':'2','Pain':'1','Neut':'0'})
data2load = pd.read_csv('/Users/dhewitt/Data/pps/electrodeGroupings.csv')
elsdf = pd.DataFrame(data2load)
df=df.join(elsdf.set_index('ElectrodeID'), on='ElectrodeID')
df

,ID,ElectrodeID,Timebin,FreqBand,EEGPowerChange,Block,Cue,Rep,Side,Grouping1,Grouping2,Grouping3,ElSide
0,2,1,1,4,14.347441,1,1,1,L,1,1,1,-1
1,2,1,1,4,10.494283,1,1,1,R,1,1,1,-1
2,2,1,1,4,13.468053,1,0,1,M,1,1,1,-1
3,2,1,1,4,1.860015,2,1,1,L,1,1,1,-1
4,2,1,1,4,8.871155,2,1,1,R,1,1,1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119803,30,32,3,24,-3.203476,1,1,2,R,1,1,10,1
119804,30,32,3,24,-14.484860,1,0,2,M,1,1,10,1
119805,30,32,3,24,-13.482171,2,1,2,L,1,1,10,1
119806,30,32,3,24,-22.069675,2,1,2,R,1,1,10,1
119807,30,32,3,24,-1.237328,2,0,2,M,1,1,10,1

In [36]:
data2load = pd.read_csv('/Users/dhewitt/Data/pps/tonicpainsides.csv')
sidesdf = pd.DataFrame(data2load).astype('int32')

In [37]:
melted_df = pd.merge(df,sidesdf, on='ID')
melted_df.drop(columns=['B2'],inplace = True)
melted_df

,ID,ElectrodeID,Timebin,FreqBand,EEGPowerChange,Block,Cue,Rep,Side,Grouping1,Grouping2,Grouping3,ElSide,B1
0,2,1,1,4,14.347441,1,1,1,L,1,1,1,-1,2
1,2,1,1,4,10.494283,1,1,1,R,1,1,1,-1,2
2,2,1,1,4,13.468053,1,0,1,M,1,1,1,-1,2
3,2,1,1,4,1.860015,2,1,1,L,1,1,1,-1,2
4,2,1,1,4,8.871155,2,1,1,R,1,1,1,-1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119803,30,32,3,24,-3.203476,1,1,2,R,1,1,10,1,2
119804,30,32,3,24,-14.484860,1,0,2,M,1,1,10,1,2
119805,30,32,3,24,-13.482171,2,1,2,L,1,1,10,1,2
119806,30,32,3,24,-22.069675,2,1,2,R,1,1,10,1,2
119807,30,32,3,24,-1.237328,2,0,2,M,1,1,10,1,2

In [38]:
##new version

# For cong DataFrame
cong_index = ((melted_df['Rep'].astype(int)==1) & (melted_df['B1'].astype(int)==1) & 
              (melted_df['Side']=='L')) | \
             ((melted_df['Rep'].astype(int)==1) & (melted_df['B1'].astype(int)==2) & 
              (melted_df['Side']=='R')) | \
             ((melted_df['Rep'].astype(int)==2) & (melted_df['B1'].astype(int)==1) & 
              (melted_df['Side']=='R')) | \
             ((melted_df['Rep'].astype(int)==2) & (melted_df['B1'].astype(int)==2) & 
              (melted_df['Side']=='L'))
cong = melted_df.loc[cong_index].copy()  # Ensure a copy is made to avoid modifying the original DataFrame
cong['congruency'] = 2

incong_index = ((melted_df['Rep'].astype(int) == 1) & (melted_df['B1'].astype(int) == 1) & 
                (melted_df['Side'] == 'R')) | \
               ((melted_df['Rep'].astype(int) == 1) & (melted_df['B1'].astype(int) == 2) & 
                (melted_df['Side'] == 'L')) | \
               ((melted_df['Rep'].astype(int) == 2) & (melted_df['B1'].astype(int) == 1) & 
                (melted_df['Side'] == 'L')) | \
               ((melted_df['Rep'].astype(int) == 2) & (melted_df['B1'].astype(int) == 2) & 
                (melted_df['Side'] == 'R'))
incong = melted_df.loc[incong_index].copy()  # Ensure a copy is made to avoid modifying the original DataFrame
incong['congruency'] = 1

neutral_index = melted_df['Side'] == 'M'
neutral = melted_df.loc[neutral_index].copy()  # Ensure a copy is made to avoid modifying the original DataFrame
neutral['congruency'] = 0

joineddf=pd.concat([neutral,cong,incong])
joineddf
joineddf_sorted = joineddf.sort_values(by='EEGPowerChange')
joineddf_sorted

,ID,ElectrodeID,Timebin,FreqBand,EEGPowerChange,Block,Cue,Rep,Side,Grouping1,Grouping2,Grouping3,ElSide,B1,congruency
93828,25,12,2,8,-88.229256,1,1,1,L,4,4,4,-1,1,2
94219,25,12,3,8,-85.013054,1,1,2,R,4,4,4,-1,1,2
10554,4,16,1,8,-82.723123,1,1,2,L,5,5,5,-1,2,2
93961,25,23,2,8,-81.821244,1,1,1,R,4,4,40,1,1,1
93835,25,12,2,8,-80.702299,1,1,2,R,4,4,4,-1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79360,21,22,3,4,424.697250,2,1,1,R,4,4,40,1,1,1
52812,14,18,3,8,521.240289,1,1,1,L,5,5,5,1,2,1
228,2,20,1,4,575.587594,1,1,1,L,4,4,40,1,2,1
9952,4,30,2,4,605.061530,2,1,1,R,1,10,10,1,2,2
52788,14,16,3,8,618.093032,1,1,1,L,5,5,5,-1,2,1

In [39]:
joineddf=joineddf.replace({'L':'1','M':'0','R':'2'})
joineddf.to_csv('/Users/dhewitt/Data/pps/Exports/ERD/PPSERDDataLong_Grouped_noav_180324.csv')
joineddf

,ID,ElectrodeID,Timebin,FreqBand,EEGPowerChange,Block,Cue,Rep,Side,Grouping1,Grouping2,Grouping3,ElSide,B1,congruency
2,2,1,1,4,13.468053,1,0,1,0,1,1,1,-1,2,0
5,2,1,1,4,29.563916,2,0,1,0,1,1,1,-1,2,0
8,2,1,1,4,11.584582,1,0,2,0,1,1,1,-1,2,0
11,2,1,1,4,32.783736,2,0,2,0,1,1,1,-1,2,0
14,2,2,1,4,23.508893,1,0,1,0,1,1,100,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119794,30,31,3,24,-7.696307,2,1,2,2,1,10,10,1,2,1
119796,30,32,3,24,-4.062452,1,1,1,1,1,1,10,1,2,1
119799,30,32,3,24,-16.279714,2,1,1,1,1,1,10,1,2,1
119803,30,32,3,24,-3.203476,1,1,2,2,1,1,10,1,2,1
119806,30,32,3,24,-22.069675,2,1,2,2,1,1,10,1,2,1

In [40]:
data2load = pd.read_csv('/Users/dhewitt/Data/pps/Exports/meanTonic.csv')
ratingsdf = pd.DataFrame(data2load)
ratingsdf

,ID,B1,TonicPainSide,Rep,MeanInt,SlopeInt,MeanUn,SlopeUn,STAI_State_Score,STAI_Trait_Score,Sex,Age,Handed,Elec_Lpain,Elec_Lunp,Elec_Rpain,Elec_Runp
0,2,2,2,1,3.90,0.067,4.82,0.121,29,37,2,32,1,4.67,6.00,4.00,5.00
1,3,1,1,1,3.40,-0.339,3.73,-0.455,27,35,1,26,1,3.67,3.67,3.33,3.67
2,4,2,2,1,4.30,-0.503,5.36,-0.491,24,41,2,22,1,5.67,7.33,5.33,7.00
3,5,1,1,1,1.55,-0.167,1.77,0.021,24,25,1,19,1,2.33,2.33,1.67,2.00
4,6,2,2,1,2.10,-0.333,2.27,-0.273,29,40,1,27,3,2.33,2.33,3.00,2.67
5,8,2,2,1,4.60,0.109,4.64,0.236,27,27,2,23,1,3.00,3.00,6.67,6.67
6,9,1,1,1,5.00,0.267,5.00,0.206,29,46,2,28,1,4.33,4.67,4.67,5.00
7,10,2,2,1,5.10,-0.115,5.91,0.067,32,51,1,38,1,5.00,5.67,6.00,6.00
8,11,1,1,1,4.10,-0.103,5.45,0.006,37,34,2,23,1,5.00,5.33,6.33,7.00
9,12,2,2,1,3.90,-0.430,5.00,-0.261,31,36,2,23,1,6.00,6.33,3.67,3.00
10,13,1,1,1,1.70,-0.152,2.09,-0.073,38,41,1,38,1,3.00,4.33,4.00,4.33
11,14,2,2,1,4.44,-0.327,4.90,-0.167,27,21,2,31,1,6.00,7.67,6.33,7.67
12,15,1,1,1,3.80,0.194,6.00,0.200,30,26,1,20,1,4.67,4.67,5.33,5.33
13,16,2,2,1,3.20,-0.291,3.45,-0.133,29,33,1,26,1,3.67,3.00,5.00,4.67
14,17,1,1,1,4.00,0.000,6.00,-0.048,28,47,1,28,1,3.33,4.33,2.00,3.00
15,19,1,1,1,3.00,-0.194,4.55,-0.164,30,28,1,21,1,3.00,3.00,3.00,3.00
16,20,2,2,1,2.00,0.036,3.64,-0.224,25,23,2,24,1,3.00,3.67,3.00,3.67
17,21,1,1,1,2.70,-0.127,3.27,-0.248,27,33,2,24,1,3.67,3.33,4.33,5.67
18,22,2,2,1,5.20,-0.085,5.18,-0.085,34,33,1,29,1,6.00,6.00,3.00,3.00
19,24,2,2,1,3.40,-0.230,3.00,-0.364,24,39,1,27,1,4.67,4.67,4.33,4.00
20,25,1,1,1,4.00,0.012,6.73,0.109,32,33,1,24,1,5.00,5.67,6.00,6.67
21,26,2,2,1,4.10,-0.042,4.91,0.085,34,48,1,20,1,5.33,5.33,6.00,6.67
22,27,1,1,1,4.60,-0.097,4.91,0.067,53,50,2,31,1,6.00,5.33,7.33,7.67
23,28,2,2,1,3.20,0.218,4.27,0.018,29,45,2,27,1,7.00,6.67,5.67,5.67
24,29,1,1,1,2.20,0.048,3.45,0.109,25,43,2,24,2,3.00,3.33,5.00,5.00
25,30,2,2,1,6.30,0.006,6.45,-0.030,41,40,2,28,1,6.00,6.33,7.33,7.67
26,2,2,1,2,4.20,-0.170,5.20,-0.170,29,37,2,32,1,4.33,5.33,3.33,4.33
27,3,1,2,2,2.60,-0.291,3.00,-0.424,27,35,1,26,1,2.00,1.67,2.00,2.00
28,4,2,1,2,4.40,-0.582,4.90,-0.758,24,41,2,22,1,4.67,5.00,4.67,5.00
29,5,1,2,2,2.20,-0.061,2.20,-0.061,24,25,1,19,1,2.00,2.00,2.00,2.00
30,6,2,1,2,2.00,-0.255,1.80,-0.158,29,40,1,27,3,2.33,2.00,2.33,2.33
31,8,2,1,2,3.22,-0.012,3.56,-0.055,27,27,2,23,1,3.67,3.33,6.67,6.67
32,9,1,2,2,4.00,-0.024,4.80,-0.133,29,46,2,28,1,4.67,4.67,5.00,5.00
33,10,2,1,2,5.00,-0.255,5.90,-0.176,32,51,1,38,1,4.67,4.00,5.67,4.00
34,11,1,2,2,5.90,0.067,6.10,0.079,37,34,2,23,1,4.00,4.33,6.67,6.67
35,12,2,1,2,3.40,-0.145,5.20,-0.073,31,36,2,23,1,5.67,6.33,2.33,3.33
36,13,1,2,2,1.70,-0.200,2.20,-0.133,38,41,1,38,1,3.33,3.33,4.00,3.67
37,14,2,1,2,3.30,-0.442,3.60,-0.376,27,21,2,31,1,3.00,5.00,7.33,7.33
38,15,1,2,2,3.70,0.091,6.20,0.182,30,26,1,20,1,4.33,4.33,4.67,4.67
39,16,2,1,2,4.00,-0.255,4.90,-0.236,29,33,1,26,1,2.67,2.00,4.33,3.67
40,17,1,2,2,3.10,-0.055,4.60,-0.073,28,47,1,28,1,3.00,3.00,2.00,2.00
41,19,1,2,2,2.60,-0.194,3.70,-0.127,30,28,1,21,1,3.67,3.00,3.00,3.00
42,20,2,1,2,1.90,-0.261,2.80,-0.339,25,23,2,24,1,3.00,3.33,3.00,3.00
43,21,1,2,2,3.50,-0.018,4.00,-0.121,27,33,2,24,1,3.00,3.33,5.67,6.00
44,22,2,1,2,5.00,0.000,5.10,-0.042,34,33,1,29,1,5.67,5.67,3.33,3.67
45,24,2,1,2,3.40,-0.133,2.30,-0.103,24,39,1,27,1,4.67,4.00,4.33,3.33
46,25,1,2,2,4.20,-0.036,6.60,-0.073,32,33,1,24,1,5.67,5.67,6.00,6.33
47,26,2,1,2,4.22,-0.073,4.89,-0.127,34,48,1,20,1,5.00,5.33,5.33,6.00
48,27,1,2,2,3.80,-0.133,3.90,-0.139,53,50,2,31,1,4.33,4.33,7.33,7.33
49,28,2,1,2,3.00,-0.267,3.80,-0.279,29,45,2,27,1,8.67,7.33,6.67,5.67
50,29,1,2,2,2.10,-0.212,2.60,-0.218,25,43,2,24,2,3.00,2.67,5.00,5.33
51,30,2,1,2,5.40,-0.012,5.40,-0.012,41,40,2,28,1,5.00,5.33,6.33,6.33

In [41]:
joineddf['Side'] = joineddf['Side'].astype('int64')
result_df = pd.merge(joineddf, ratingsdf, on=['ID', 'B1', 'Rep'])

In [42]:
result_df['STAI_Total'] = result_df['STAI_State_Score']+result_df['STAI_Trait_Score']

result_df.sort_values(by='EEGPowerChange').head()

,ID,ElectrodeID,Timebin,FreqBand,EEGPowerChange,Block,Cue,Rep,Side,Grouping1,...,STAI_State_Score,STAI_Trait_Score,Sex,Age,Handed,Elec_Lpain,Elec_Lunp,Elec_Rpain,Elec_Runp,STAI_Total
93206,25,12,2,8,-88.229256,1,1,1,1,4,...,32,33,1,24,1,5.00,5.67,6.00,6.67,65
95574,25,12,3,8,-85.013054,1,1,2,2,4,...,32,33,1,24,1,5.67,5.67,6.00,6.33,65
12510,4,16,1,8,-82.723123,1,1,2,1,5,...,24,41,2,22,1,4.67,5.00,4.67,5.00,65
93996,25,23,2,8,-81.821244,1,1,1,2,4,...,32,33,1,24,1,5.00,5.67,6.00,6.67,65
95510,25,12,2,8,-80.702299,1,1,2,2,4,...,32,33,1,24,1,5.67,5.67,6.00,6.33,65

In [43]:
result_df.to_csv('/Users/dhewitt/Data/pps/Exports/ERD/PPSERDDataLong_Grouped_noav_withratings_180324.csv')

In [44]:
result_df

,ID,ElectrodeID,Timebin,FreqBand,EEGPowerChange,Block,Cue,Rep,Side,Grouping1,...,STAI_State_Score,STAI_Trait_Score,Sex,Age,Handed,Elec_Lpain,Elec_Lunp,Elec_Rpain,Elec_Runp,STAI_Total
0,2,1,1,4,13.468053,1,0,1,0,1,...,29,37,2,32,1,4.67,6.00,4.00,5.00,66
1,2,1,1,4,29.563916,2,0,1,0,1,...,29,37,2,32,1,4.67,6.00,4.00,5.00,66
2,2,2,1,4,23.508893,1,0,1,0,1,...,29,37,2,32,1,4.67,6.00,4.00,5.00,66
3,2,2,1,4,2.720218,2,0,1,0,1,...,29,37,2,32,1,4.67,6.00,4.00,5.00,66
4,2,3,1,4,17.448463,1,0,1,0,1,...,29,37,2,32,1,4.67,6.00,4.00,5.00,66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119803,30,30,3,24,-13.841429,2,1,2,2,1,...,41,40,2,28,1,5.00,5.33,6.33,6.33,81
119804,30,31,3,24,-12.453795,1,1,2,2,1,...,41,40,2,28,1,5.00,5.33,6.33,6.33,81
119805,30,31,3,24,-7.696307,2,1,2,2,1,...,41,40,2,28,1,5.00,5.33,6.33,6.33,81
119806,30,32,3,24,-3.203476,1,1,2,2,1,...,41,40,2,28,1,5.00,5.33,6.33,6.33,81
119807,30,32,3,24,-22.069675,2,1,2,2,1,...,41,40,2,28,1,5.00,5.33,6.33,6.33,81

# Adding VR data

In [45]:
## Loading VR Data now - keeping phase column and renaming to timebin to match EEG data

data2load = pd.read_csv('/Users/dhewitt/Data/pps/Exports/PupilDiameter/GrandAvExport_PupilDiameterExtLong_Recoded_phaseav.csv')
pupilDiameter = pd.DataFrame(data2load)

data2load = pd.read_csv('/Users/dhewitt/Data/pps/Exports/GazeDirection/GrandAvExport_GazeDirExtLong_Recoded_phaseav.csv')
gazeDirection = pd.DataFrame(data2load)

VRdf = pd.merge(pupilDiameter, gazeDirection, on=['ID','Phase','Side','Rep','Condition'])
VRdf = VRdf.rename({'Measure_x' : 'PupilDiameter',
                    'Measure_y' : 'GazeDirection',
                   'Phase' : 'Timebin', 'Condition' : 'Block'}, axis=1)
#VRdf['Timebin'].replace({2:1,3:2}, inplace=True)
VRdf= VRdf.replace({'L':'1','M':'0','R':'2','C':'1','E':'2'})
VRdf = VRdf.astype('float64') # convert to numeric data types

In [46]:
pupilDiameter

     ID  Phase Side  Rep Condition   Measure
0     2      1    L    1         C -0.026164
1     2      1    L    1         E  0.015512
2     2      1    L    2         C  0.012170
3     2      1    L    2         E -0.006592
4     2      1    M    1         C  0.032822
..   ..    ...  ...  ...       ...       ...
931  30      3    M    2         E -0.064493
932  30      3    R    1         C  0.120285
933  30      3    R    1         E -0.008445
934  30      3    R    2         C  0.056724
935  30      3    R    2         E -0.125147

[936 rows x 6 columns]

In [47]:
# Get all columns which are of the 'object' dtype before merging
object_columns = result_df.select_dtypes(include=['object']).columns
result_df[object_columns] = result_df[object_columns].astype('int64')
result_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 119808 entries, 0 to 119807
Data columns (total 30 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   ID                119808 non-null  int64
 1   ElectrodeID       119808 non-null  int64
 2   Timebin           119808 non-null  int64
 3   FreqBand          119808 non-null  int64
 4   EEGPowerChange    119808 non-null  float64
 5   Block             119808 non-null  int64
 6   Cue               119808 non-null  int64
 7   Rep               119808 non-null  int64
 8   Side              119808 non-null  int64
 9   Grouping1         119808 non-null  int64
 10  Grouping2         119808 non-null  int64
 11  Grouping3         119808 non-null  int64
 12  ElSide            119808 non-null  int64
 13  B1                119808 non-null  int32
 14  congruency        119808 non-null  int64
 15  TonicPainSide     119808 non-null  int64
 16  MeanInt           119808 non-null  float64
 17  SlopeInt          119808 non-null  float64
 18  MeanUn            119808 non-null  float64
 19  SlopeUn           119808 non-null  float64
 20  STAI_State_Score  119808 non-null  int64
 21  STAI_Trait_Score  119808 non-null  int64
 22  Sex               119808 non-null  int64
 23  Age               119808 non-null  int64
 24  Handed            119808 non-null  int64
 25  Elec_Lpain        119808 non-null  float64
 26  Elec_Lunp         119808 non-null  float64
 27  Elec_Rpain        119808 non-null  float64
 28  Elec_Runp         119808 non-null  float64
 29  STAI_Total        119808 non-null  int64
dtypes: float64(9), int32(1), int64(20)
memory usage: 27.9 MB

In [48]:
new_result_df = pd.merge(result_df, VRdf, on=['ID', 'Timebin', 'Side','Rep','Block'])
new_result_df

,ID,ElectrodeID,Timebin,FreqBand,EEGPowerChange,Block,Cue,Rep,Side,Grouping1,...,Sex,Age,Handed,Elec_Lpain,Elec_Lunp,Elec_Rpain,Elec_Runp,STAI_Total,PupilDiameter,GazeDirection
0,2,1,1,4,13.468053,1,0,1,0,1,...,2,32,1,4.67,6.00,4.00,5.00,66,0.032822,17.803805
1,2,2,1,4,23.508893,1,0,1,0,1,...,2,32,1,4.67,6.00,4.00,5.00,66,0.032822,17.803805
2,2,3,1,4,17.448463,1,0,1,0,1,...,2,32,1,4.67,6.00,4.00,5.00,66,0.032822,17.803805
3,2,4,1,4,33.243642,1,0,1,0,1,...,2,32,1,4.67,6.00,4.00,5.00,66,0.032822,17.803805
4,2,5,1,4,48.008915,1,0,1,0,2,...,2,32,1,4.67,6.00,4.00,5.00,66,0.032822,17.803805
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119803,30,28,3,24,-4.956157,2,1,2,2,3,...,2,28,1,5.00,5.33,6.33,6.33,81,-0.125147,7.172001
119804,30,29,3,24,-10.990969,2,1,2,2,3,...,2,28,1,5.00,5.33,6.33,6.33,81,-0.125147,7.172001
119805,30,30,3,24,-13.841429,2,1,2,2,1,...,2,28,1,5.00,5.33,6.33,6.33,81,-0.125147,7.172001
119806,30,31,3,24,-7.696307,2,1,2,2,1,...,2,28,1,5.00,5.33,6.33,6.33,81,-0.125147,7.172001
119807,30,32,3,24,-22.069675,2,1,2,2,1,...,2,28,1,5.00,5.33,6.33,6.33,81,-0.125147,7.172001

In [49]:
new_result_df.to_csv('/Users/dhewitt/Data/pps/Exports/ERD/PPSERDDataLong_Grouped_noav_withratings_180324.csv')

# Now sorting the data by contra - ipsi

In [50]:
cue_left = new_result_df[new_result_df['Side'] == 1]
cue_right = new_result_df[new_result_df['Side'] == 2]

In [51]:
cue_left_contra = cue_left[cue_left['ElSide'] == 1].copy()
cue_left_ipsi = cue_left[cue_left['ElSide'] == -1].copy()
cue_left_contra = cue_left_contra.reset_index(drop=True)
cue_left_ipsi = cue_left_ipsi.reset_index(drop=True)
cue_left_contra_ratio = cue_left_contra.copy()
cue_left_contra_ratio['CIRatio'] = (cue_left_contra['EEGPowerChange'] - cue_left_ipsi['EEGPowerChange'])/(cue_left_contra['EEGPowerChange'] + cue_left_ipsi['EEGPowerChange'])
cue_left_contra_ratio

,ID,ElectrodeID,Timebin,FreqBand,EEGPowerChange,Block,Cue,Rep,Side,Grouping1,...,Age,Handed,Elec_Lpain,Elec_Lunp,Elec_Rpain,Elec_Runp,STAI_Total,PupilDiameter,GazeDirection,CIRatio
0,2,18,1,4,10.474399,1,1,1,1,5,...,32,1,4.67,6.00,4.00,5.00,66,-0.026164,16.254906,-0.156034
1,2,19,1,4,76.279914,1,1,1,1,4,...,32,1,4.67,6.00,4.00,5.00,66,-0.026164,16.254906,1.246885
2,2,20,1,4,575.587594,1,1,1,1,4,...,32,1,4.67,6.00,4.00,5.00,66,-0.026164,16.254906,0.842699
3,2,21,1,4,76.057749,1,1,1,1,6,...,32,1,4.67,6.00,4.00,5.00,66,-0.026164,16.254906,0.291818
4,2,22,1,4,55.959065,1,1,1,1,4,...,32,1,4.67,6.00,4.00,5.00,66,-0.026164,16.254906,-0.025728
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17467,30,28,3,24,1.920386,2,1,2,1,3,...,28,1,5.00,5.33,6.33,6.33,81,-0.096616,5.232378,-1.141486
17468,30,29,3,24,-16.107204,2,1,2,1,3,...,28,1,5.00,5.33,6.33,6.33,81,-0.096616,5.232378,-0.086495
17469,30,30,3,24,0.434459,2,1,2,1,1,...,28,1,5.00,5.33,6.33,6.33,81,-0.096616,5.232378,-2.022618
17470,30,31,3,24,17.803665,2,1,2,1,1,...,28,1,5.00,5.33,6.33,6.33,81,-0.096616,5.232378,-2.352111
17471,30,32,3,24,-13.482171,2,1,2,1,1,...,28,1,5.00,5.33,6.33,6.33,81,-0.096616,5.232378,-0.423687

In [52]:
cue_right_contra = cue_right[cue_right['ElSide'] == -1].copy()
cue_right_ipsi = cue_right[cue_right['ElSide'] == 1].copy()
cue_right_contra = cue_right_contra.reset_index(drop=True)
cue_right_ipsi = cue_right_ipsi.reset_index(drop=True)
cue_right_contra_ratio = cue_right_contra.copy()
cue_right_contra_ratio['CIRatio'] = (cue_right_contra['EEGPowerChange'] - cue_right_ipsi['EEGPowerChange'])/(cue_right_contra['EEGPowerChange'] + cue_right_ipsi['EEGPowerChange'])

In [53]:
new_result_df

,ID,ElectrodeID,Timebin,FreqBand,EEGPowerChange,Block,Cue,Rep,Side,Grouping1,...,Sex,Age,Handed,Elec_Lpain,Elec_Lunp,Elec_Rpain,Elec_Runp,STAI_Total,PupilDiameter,GazeDirection
0,2,1,1,4,13.468053,1,0,1,0,1,...,2,32,1,4.67,6.00,4.00,5.00,66,0.032822,17.803805
1,2,2,1,4,23.508893,1,0,1,0,1,...,2,32,1,4.67,6.00,4.00,5.00,66,0.032822,17.803805
2,2,3,1,4,17.448463,1,0,1,0,1,...,2,32,1,4.67,6.00,4.00,5.00,66,0.032822,17.803805
3,2,4,1,4,33.243642,1,0,1,0,1,...,2,32,1,4.67,6.00,4.00,5.00,66,0.032822,17.803805
4,2,5,1,4,48.008915,1,0,1,0,2,...,2,32,1,4.67,6.00,4.00,5.00,66,0.032822,17.803805
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119803,30,28,3,24,-4.956157,2,1,2,2,3,...,2,28,1,5.00,5.33,6.33,6.33,81,-0.125147,7.172001
119804,30,29,3,24,-10.990969,2,1,2,2,3,...,2,28,1,5.00,5.33,6.33,6.33,81,-0.125147,7.172001
119805,30,30,3,24,-13.841429,2,1,2,2,1,...,2,28,1,5.00,5.33,6.33,6.33,81,-0.125147,7.172001
119806,30,31,3,24,-7.696307,2,1,2,2,1,...,2,28,1,5.00,5.33,6.33,6.33,81,-0.125147,7.172001
119807,30,32,3,24,-22.069675,2,1,2,2,1,...,2,28,1,5.00,5.33,6.33,6.33,81,-0.125147,7.172001

In [54]:
contra_ipsi_df = pd.concat([cue_left_contra_ratio,cue_right_contra_ratio])

In [55]:
contra_ipsi_df

,ID,ElectrodeID,Timebin,FreqBand,EEGPowerChange,Block,Cue,Rep,Side,Grouping1,...,Age,Handed,Elec_Lpain,Elec_Lunp,Elec_Rpain,Elec_Runp,STAI_Total,PupilDiameter,GazeDirection,CIRatio
0,2,18,1,4,10.474399,1,1,1,1,5,...,32,1,4.67,6.00,4.00,5.00,66,-0.026164,16.254906,-0.156034
1,2,19,1,4,76.279914,1,1,1,1,4,...,32,1,4.67,6.00,4.00,5.00,66,-0.026164,16.254906,1.246885
2,2,20,1,4,575.587594,1,1,1,1,4,...,32,1,4.67,6.00,4.00,5.00,66,-0.026164,16.254906,0.842699
3,2,21,1,4,76.057749,1,1,1,1,6,...,32,1,4.67,6.00,4.00,5.00,66,-0.026164,16.254906,0.291818
4,2,22,1,4,55.959065,1,1,1,1,4,...,32,1,4.67,6.00,4.00,5.00,66,-0.026164,16.254906,-0.025728
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17467,30,11,3,24,-8.696123,2,1,2,2,4,...,28,1,5.00,5.33,6.33,6.33,81,-0.125147,7.172001,0.273944
17468,30,12,3,24,0.719471,2,1,2,2,4,...,28,1,5.00,5.33,6.33,6.33,81,-0.125147,7.172001,-1.140091
17469,30,14,3,24,0.543570,2,1,2,2,4,...,28,1,5.00,5.33,6.33,6.33,81,-0.125147,7.172001,-1.081753
17470,30,15,3,24,-19.234972,2,1,2,2,4,...,28,1,5.00,5.33,6.33,6.33,81,-0.125147,7.172001,0.428448
17471,30,16,3,24,-13.419250,2,1,2,2,5,...,28,1,5.00,5.33,6.33,6.33,81,-0.125147,7.172001,-0.243750

In [56]:
contra_ipsi_df.to_csv('/Users/dhewitt/Data/pps/Exports/ERD/PPSERDDataLong_Grouped_noav_withratings_CIR_180324.csv')

In [57]:
cue_left_contra['ElHem'] = 1
cue_left_ipsi['ElHem'] = -1
cue_right_contra['ElHem'] = 1
cue_right_ipsi['ElHem'] = -1
elhem_df = pd.concat([cue_left_contra, cue_left_ipsi, cue_right_contra, cue_right_ipsi])
elhem_df

,ID,ElectrodeID,Timebin,FreqBand,EEGPowerChange,Block,Cue,Rep,Side,Grouping1,...,Age,Handed,Elec_Lpain,Elec_Lunp,Elec_Rpain,Elec_Runp,STAI_Total,PupilDiameter,GazeDirection,ElHem
0,2,18,1,4,10.474399,1,1,1,1,5,...,32,1,4.67,6.00,4.00,5.00,66,-0.026164,16.254906,1
1,2,19,1,4,76.279914,1,1,1,1,4,...,32,1,4.67,6.00,4.00,5.00,66,-0.026164,16.254906,1
2,2,20,1,4,575.587594,1,1,1,1,4,...,32,1,4.67,6.00,4.00,5.00,66,-0.026164,16.254906,1
3,2,21,1,4,76.057749,1,1,1,1,6,...,32,1,4.67,6.00,4.00,5.00,66,-0.026164,16.254906,1
4,2,22,1,4,55.959065,1,1,1,1,4,...,32,1,4.67,6.00,4.00,5.00,66,-0.026164,16.254906,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17467,30,28,3,24,-4.956157,2,1,2,2,3,...,28,1,5.00,5.33,6.33,6.33,81,-0.125147,7.172001,-1
17468,30,29,3,24,-10.990969,2,1,2,2,3,...,28,1,5.00,5.33,6.33,6.33,81,-0.125147,7.172001,-1
17469,30,30,3,24,-13.841429,2,1,2,2,1,...,28,1,5.00,5.33,6.33,6.33,81,-0.125147,7.172001,-1
17470,30,31,3,24,-7.696307,2,1,2,2,1,...,28,1,5.00,5.33,6.33,6.33,81,-0.125147,7.172001,-1
17471,30,32,3,24,-22.069675,2,1,2,2,1,...,28,1,5.00,5.33,6.33,6.33,81,-0.125147,7.172001,-1

In [58]:
elhem_df.to_csv('/Users/dhewitt/Data/pps/Exports/ERD/PPSERDDataLong_Grouped_noav_withratings_elhem_180324.csv')